Feature/about
Viktor-Kostiuchenko/team-project pull request #16
Opened 2021-07-05 19:32 UTC by LarysaTymoshenko

В десктоп грузится картинка другого формата

2021-07-05 20:43 UTC, Viktor-Kostiuchenko commented on src/sass/layout/_about.scss
> +.about-title {
Там в body изменили основной цвет на сероватый. Поэтому по всей секции нужно пройтись и вручную задать черный

2021-07-05 20:49 UTC, Viktor-Kostiuchenko commented on src/partials/about.html
> +<section class="about">
Секции about задать padding. Тогда секции будут модульными (их можно будет из места в место перемещать и все будет оставаться красиво) 

По макету конечно сложно наверняка понять какие падинги, но ориентировочно: 
Мобилка: верхний 20, нижний 25
Таблетка: верхний 65, нижний 65
Десктоп: верхний 65, нижний 65

2021-07-05 20:54 UTC, Viktor-Kostiuchenko commented on src/sass/layout/_about.scss
> +.about-picture {
Класс задается на тег img, а не picture.
попробуй перезадать. Потому как картинка не становится в правильном размере. Она маленькая

2021-07-05 20:58 UTC, Viktor-Kostiuchenko commented on src/sass/layout/_about.scss
> +.about-title {
И здесь же проверь заданный font-size по всем точкам (мобилке, таблетке, десктопе) 
Должно быть 20, 26 и 46 соответственно

2021-07-05 20:59 UTC, Viktor-Kostiuchenko commented on src/sass/layout/_about.scss
> +.about-name {
И здесь же проверь заданный font-size по всем точкам (мобилке, таблетке, десктопе)
Должно быть 20, 20 и 30 соответственно

2021-07-05 21:15 UTC, Viktor-Kostiuchenko commented on src/sass/layout/_about.scss
> +  &::after {
Вот это нижнее подчеркивание лучше сделать как border-bottom а не через псевдоэлемент after.
Тогда можно будет как раз этот заголовок отцентрировать. А сейчас - он приподнят к картинке и стоит не по центру

2021-07-05 21:21 UTC, Viktor-Kostiuchenko commented on src/partials/about.html
> +                <svg class="about-check" width="17" height="14">
Переделать иконки.
в тз написано "Иконки списка выполнить псевдоэлементами. Изображение иконки сохранить в svg формате.", а не через встроенные svg как сейчас

2021-07-05 21:25 UTC, Viktor-Kostiuchenko commented on src/partials/about.html
> +                <svg class="about-check" width="17" height="14">
+ убедись, чтобы подгрузились нормального размера

2021-07-05 21:36 UTC, Viktor-Kostiuchenko commented on src/partials/about.html
> +        <picture class="about-picture">
вот здесь нужно поменять порядок написанных source
Сначала для дестопа, потом для таблетки и в конце для мобилки (то есть от большего к меньшему) 
Иначе - не будет подтягивать десктопную картинку

2021-07-05 21:37 UTC, Viktor-Kostiuchenko commented on src/sass/layout/_about.scss
> +  &::after {
Плюс бордер тогда будет растягиваться на всю ширину блока, а сейчас - он не на всю

2021-07-06 09:32 UTC, LarysaTymoshenko commented on src/partials/about.html
> +<section class="about">
хорошо, падинги сделаю. Мне б с картинкой разобраться

2021-07-06 09:35 UTC, LarysaTymoshenko commented on src/sass/layout/_about.scss
> +.about-name {
+

2021-07-06 22:51 UTC, vladislav-slobodenjuk requested changes

2021-07-06 22:51 UTC, vladislav-slobodenjuk commented on src/partials/about.html
> +        <h2 class="about-title">Teacher</h2>
Ставим здесь класс title и большая часть стилей подтянется, чего не хватает добавим в ручную

2021-07-06 22:51 UTC, vladislav-slobodenjuk commented on src/sass/layout/_about.scss
> +  padding-top:20px;
Верхний падинг 40, нижний надо убрать

2021-07-06 22:51 UTC, vladislav-slobodenjuk commented on src/sass/layout/_about.scss
> +  font-weight: 800;
font-size: 20px;
  font-weight: 800;
  letter-spacing: 0.03em;
  line-height: 1.3;
Не нужны, Подтянется по классу title в html

2021-07-06 22:51 UTC, vladislav-slobodenjuk commented on src/partials/about.html
> +        <ul class="about-list">
Добавить класс list - уберутся точки у лишек

2021-07-06 22:51 UTC, vladislav-slobodenjuk commented on src/partials/about.html
> +        <h3 class="about-name">Elena Moreva</h3>
добавить класс title

2021-07-06 22:51 UTC, vladislav-slobodenjuk commented on src/sass/layout/_about.scss
> +  display: block;
Добавить класс title в html

Убрать
  display: block;
  font-size: 20px;
  font-weight: 800;
  width: 280px;
  color: $primary-black-color;

2021-07-06 22:51 UTC, vladislav-slobodenjuk commented on src/sass/layout/_about.scss
> +  padding-top: 10px;
падинг топ тоже не нужен

2021-07-06 22:51 UTC, vladislav-slobodenjuk commented on src/sass/layout/_about.scss
> +  width: 280px;
убрать ширину

2021-07-06 22:51 UTC, vladislav-slobodenjuk commented on src/sass/layout/_about.scss
> +
на этапе мобильного .about-list надо добавить левый марджин 25 чтобы галочки стали в один ряд в шириной контейнера

2021-07-06 22:51 UTC, vladislav-slobodenjuk commented on src/sass/layout/_about.scss
> +  display: flex;
на этапе мобильного флекс здесь не нужен. Лучше вписать уже в медиа 768

2021-07-06 22:51 UTC, vladislav-slobodenjuk commented on src/sass/layout/_about.scss
> +  &::after {
Это бифор следующего абзаца, а не афтер списка. Левый марджин перед списком не даст афтеру стать на правильное место. Под это выровнять и верхние/нижние отступы списка, бифора и абзаца

2021-07-06 22:51 UTC, vladislav-slobodenjuk commented on src/sass/layout/_about.scss
> +  font-size: 12px;
font-size: 10px;

2021-07-06 22:51 UTC, vladislav-slobodenjuk commented on src/sass/layout/_about.scss
> +  color: $primary-text-color;
для боди это цввет и так задан, можно убрать

2021-07-06 22:51 UTC, vladislav-slobodenjuk commented on src/sass/layout/_about.scss
> +  text-align: left;
text-align: left; Это значение по умолчанию, можно убрать

2021-07-06 22:51 UTC, vladislav-slobodenjuk commented on src/partials/about.html
> +        <p class="text-descr">
Переставь правильный размер шрифта и возможно не придется разбивать на несколько абзацев

2021-07-06 22:51 UTC, vladislav-slobodenjuk commented on src/partials/about.html
> +            <p class="text-descr">
поправить правильную вложенность

2021-07-06 22:51 UTC, vladislav-slobodenjuk commented on src/sass/layout/_about.scss
> +}
нужно задать падинг ботом 24 последнему абзацу, либо единственному если объединишь их

2021-07-06 22:51 UTC, vladislav-slobodenjuk commented on src/sass/layout/_about.scss
> +    margin-right: 40px;
после добавления марджин лефт списку здесь уже не надо

2021-07-06 22:51 UTC, vladislav-slobodenjuk commented on src/sass/layout/_about.scss
> +    padding-top:65px;
верхний 50, нижний убрать

2021-07-06 22:51 UTC, vladislav-slobodenjuk commented on src/sass/layout/_about.scss
> +    width: 401px;
width: 401px; лишнее

2021-07-06 22:51 UTC, vladislav-slobodenjuk commented on src/sass/layout/_about.scss
> +    width: 640px;
width: 640px; лишнее

2021-07-06 22:51 UTC, vladislav-slobodenjuk commented on src/sass/layout/_about.scss
> +    margin-top: 20px;
это должен быть марджин ботом у абзаца выше

2021-07-06 23:04 UTC, vladislav-slobodenjuk commented on src/partials/about.html
> +    </div>
и тут вложенность

2021-07-07 08:53 UTC, LarysaTymoshenko commented on src/sass/layout/_about.scss
> +    width: 401px;
Тогда  нижний бордер  только на длину  заголовка (имени), а на макете длиннее сама полоска

2021-07-07 09:24 UTC, LarysaTymoshenko commented on src/partials/about.html
> +    </div>
Что  тут не так?

2021-07-07 13:59 UTC, vladislav-slobodenjuk commented on src/partials/about.html
> +    </div>
Дивы в столбик стоят. Должны быть отступы по вложенности

2021-07-07 23:16 UTC, closed without merging