Feature/header
Viktor-Kostiuchenko/team-project pull request #21
Opened 2021-07-06 00:40 UTC by Saftar94

Add header & Add footer

2021-07-06 08:37 UTC, Viktor-Kostiuchenko requested changes

2021-07-06 08:37 UTC, Viktor-Kostiuchenko commented on src/images/icons/menu.svg
> +<svg aria-hidden="true" style="position: absolute; width: 20; height: 20; overflow: hidden;" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
Я пока только по самому коду могу пройтись. А ближе к 18:00 уже смогу полноценно глянуть. Может кто-то из ребят (я им дал доступ на review) смогут это раньше чем 18:00 сделать

2021-07-06 08:37 UTC, Viktor-Kostiuchenko commented on src/partials/footer.html
> +<footer class="footer-title">
Я сейчас по классам пройдусь. Чтобы они корректно описывали содержимое тега. 
Просто эти классы перенеси в scss файл

2021-07-06 08:37 UTC, Viktor-Kostiuchenko commented on src/partials/footer.html
> +<footer class="footer-title">
Здесь задай просто класс "footer"

2021-07-06 08:37 UTC, Viktor-Kostiuchenko commented on src/partials/footer.html
> +    <div class="footer-main container">
footer-main -> footer-container

2021-07-06 08:37 UTC, Viktor-Kostiuchenko commented on src/partials/footer.html
> +        <p class="avtor">@ All rights reserved, 2019</p>
avtor -> copyright

2021-07-06 08:37 UTC, Viktor-Kostiuchenko commented on src/partials/footer.html
> +            <img class="image-instagram" alt="instagram" src="../src/images/icons/instagram.svg" width="40" height="40">
image-instagram -> instagram-icon (хоть там по факту ты добавил не иконку)

2021-07-06 08:37 UTC, Viktor-Kostiuchenko commented on src/partials/header.html
> +    <div class="header-wrappe container">
header-wrappe -> header-container

2021-07-06 08:37 UTC, Viktor-Kostiuchenko commented on src/partials/header.html
> +        <nav class="headernav">
headernav -> header-nav

2021-07-06 08:37 UTC, Viktor-Kostiuchenko commented on src/partials/header.html
> +            <a class="desklogo">HELL<span class="deslogosvg">
desklogo -> logo

deslogossvg - вообще нужен здесь этот span?

2021-07-06 08:37 UTC, Viktor-Kostiuchenko commented on src/partials/header.html
> +                <svg class="desk-svghead"  width="22" height="30">
desk-svghead -> logo-icon

2021-07-06 08:37 UTC, Viktor-Kostiuchenko commented on src/partials/header.html
> +            <p class="head-footer">HELLISH<span class="headernav-down"> ENGLISH</span></p>
head-footer -> logo-text
headernavdown -> logo-text-accent

2021-07-06 08:37 UTC, Viktor-Kostiuchenko commented on src/partials/footer.html
> +        <object class="instagram" type="image/svg+xml" data="../src/images/icons/instagram.svg">
Через тег object? Хм..не встречал ранее такого

2021-07-06 08:37 UTC, Viktor-Kostiuchenko commented on src/partials/footer.html
> +    <div class="fotar-end">
fotar-end -> copyright-wrapper

2021-07-06 08:37 UTC, Viktor-Kostiuchenko commented on src/partials/header.html
> +            <ul class="headernav-title hero">
headernav-title -> header-nav-list

hero -> list

2021-07-06 08:37 UTC, Viktor-Kostiuchenko commented on src/partials/header.html
> +                <li class="head-link"><a class="head-main headermenu-current" href="#">STUDING PROGRAM</a></li>
head-link -> header-nav-item
head-main -> header-nav-link
headermenu-current -> current

2021-07-06 08:37 UTC, Viktor-Kostiuchenko commented on src/partials/header.html
> +        <button type="button" class="order-button">CONSULTATION BY PHONE</button>
Не нужно капсом текст. 
На классе button и так стоит свойство с uppercase

2021-07-06 08:37 UTC, Viktor-Kostiuchenko commented on src/partials/header.html
> +                <li class="head-link"><a class="head-main" href="#">ABOUT</a></li>
Убери текст капсом и просто задай правило на линк text-transform: uppercase

2021-07-06 08:37 UTC, Viktor-Kostiuchenko commented on src/partials/header.html
> +            <svg class="iconhead" width="21" height="12">
iconhead -> menu-icon

2021-07-06 08:37 UTC, Viktor-Kostiuchenko commented on src/partials/header.html
> +            <ul class="mobilehero hero">
mobilehero -> mobile-menu
hero -> list

2021-07-06 08:37 UTC, Viktor-Kostiuchenko commented on src/partials/header.html
> +                <li class="mobile-item"><a class="mobile-link  mobilemenu-current" href="#">Studying program</a></li>
mobile-item -> mobile-menu-item

mobile-link -> mobile-menu-link

mobilemenu-current -> current

2021-07-06 08:37 UTC, Viktor-Kostiuchenko commented on src/partials/header.html
> +        <div class="mobile-headermenu container">
mobile-headermenu -> mobile-menu-container

2021-07-06 08:37 UTC, Viktor-Kostiuchenko commented on src/partials/header.html
> +            <a class="mobile-logo">HELL<span class="mobile-logosvg">
А там отличается иконка для мобильного меню от всех остальных? 
Просто не совсем пойму зачем разные классы на всех лого. Просто задаёшь основные правила для logo, а там где нужно немного подправить - пишешь доп.класс по типу mobile-menu-logo

2021-07-06 08:37 UTC, Viktor-Kostiuchenko commented on src/partials/header.html
> +                <svg class="mobile-svghead"  width="22" height="30">
mobile-svghead -> mobile-icon (если нужно отдельный класс)

2021-07-06 08:37 UTC, Viktor-Kostiuchenko commented on src/partials/header.html
> +            <p class="head-footer">HELLISH<span class="mobiledown">ENGLISH</span></p>
head-footer -> logo-text
headernavdown -> logo-text-accent

2021-07-06 08:37 UTC, Viktor-Kostiuchenko commented on src/partials/footer.html
> +        <p class="head-footer">HELLISH<span class="headernav-down"> ENGLISH</span></p>
head-footer -> logo-text
headernavdown -> logo-text-accent

2021-07-06 08:37 UTC, Viktor-Kostiuchenko commented on src/partials/footer.html
> +        <a class="desk-footerlogo">HELL<span class="deslogosvg">
desklogo -> logo

deslogossvg - вообще нужен здесь этот span?

2021-07-06 08:37 UTC, Viktor-Kostiuchenko commented on src/partials/header.html
> +                <svg class="iconheadclose" width="15" height="15">
iconheadclose -> close-icon

2021-07-06 08:37 UTC, Viktor-Kostiuchenko commented on src/partials/header.html
> +            <button type="button" class="mobileorder-button">CONSULTATION BY PHONE</button>
Посмотри нужно ли тебе что-то использовать для класса mobileorder-button, при условии, что уже описан и так для всех класс button?
Если нужно - оставь только то что нужно и перепиши класс на mobile-menu-button

2021-07-07 07:45 UTC, Viktor-Kostiuchenko requested changes

2021-07-07 07:45 UTC, Viktor-Kostiuchenko commented on src/partials/footer.html
> +<div class="footer-container container">
не совсем пойму почему у тебя отдельно идет footer-container от footer? 
Он должен быть внутри!

2021-07-07 07:45 UTC, Viktor-Kostiuchenko commented on src/partials/header.html
> +    <div class="header-wrappe container">
Вот здесь не обновил класс

2021-07-07 07:45 UTC, Viktor-Kostiuchenko commented on src/partials/header.html
> +            <ul class="header-nav-list hero">
почему hero? у нас же есть класс list для этого

2021-07-07 07:45 UTC, Viktor-Kostiuchenko commented on src/sass/components/_button.scss
> +.mobileorder-button{
есть же у полностью описанная кнопка. В этот класс добавь только! то что отличается от основной кнопки

2021-07-07 07:45 UTC, Viktor-Kostiuchenko commented on src/sass/components/_button.scss
> +.mobileorder-button{
а именно color, background-color и border

2021-07-07 07:45 UTC, Viktor-Kostiuchenko commented on src/partials/header.html
> +            <ul class="mobilehero hero">
mobilehero -> mobile-list
hero -> list

2021-07-07 07:45 UTC, Viktor-Kostiuchenko commented on src/sass/layout/_footer.scss
> +.desk-footerlogo{
есть же отдельный паршал logo.scss в который ты просто вырезаешь все что касается лого и вставляешь туда

2021-07-07 07:45 UTC, Viktor-Kostiuchenko commented on src/sass/layout/_footer.scss
> +.avtor{
Этот класс к чему относится в футере?

2021-07-07 07:45 UTC, Viktor-Kostiuchenko commented on src/sass/layout/_footer.scss
> +.fotar-end{
Этот класс к чему относится в футере?

2021-07-07 09:00 UTC, Bronislav-frontend approved these changes

2021-07-07 09:29 UTC, Viktor-Kostiuchenko approved these changes

2021-07-07 09:33 UTC, merged