Feature/problems
Viktor-Kostiuchenko/team-project pull request #9
Opened 2021-07-04 12:17 UTC by vladislav-slobodenjuk

Секция Problems и закомментированный аутлайн для контейнера

2021-07-04 13:44 UTC, vladislav-slobodenjuk commented
Забыл

2021-07-04 13:47 UTC, vladislav-slobodenjuk commented
Забыл добавить иконку огня, но наверно сейчас тратить время на её позиционирование не буду. Лучше больше сделаю в следующей секции

2021-07-04 20:36 UTC, Viktor-Kostiuchenko commented on src/sass/base/_container.scss
> +  // outline: 2px solid red;
Вот этот коммент не забыть убрать

2021-07-04 20:38 UTC, Viktor-Kostiuchenko commented on src/sass/layout/_problems.scss
> +  // font-size: 24px; at the maquette
и вот этот (но если они тебе все еще нужны - то потом можно это сделать)

2021-07-04 20:40 UTC, Viktor-Kostiuchenko commented on src/sass/layout/_problems.scss
> +.problems-title {
Там по макету надо глянуть по переносам слов, они, скажем, "интересно" выполнены

2021-07-04 20:42 UTC, Viktor-Kostiuchenko commented on src/sass/layout/_problems.scss
> +.problems-list-block {
Наверное это в большей степени вопрос к макету... но я бы задал этой секции равные падинги по сторонам, так красивее выглядит. В принципе, если задать по 20px - особо ничего не изменится

2021-07-04 20:59 UTC, vladislav-slobodenjuk commented on src/sass/base/_container.scss
> +  // outline: 2px solid red;
Я думал если комментарий не мешает оставить его там. Обычно использую аутлайн для контроля. Но если не стоит, то уберу

2021-07-04 21:01 UTC, vladislav-slobodenjuk commented on src/sass/layout/_problems.scss
> +  // font-size: 24px; at the maquette
Это у меня были сомнения еще по англ макету. Проклацал все заголовки - они одинакового размера кроме двух. На этом и еще одном. Оставил себе как пометку на "подумать" что с ними делать

2021-07-04 21:01 UTC, vladislav-slobodenjuk commented on src/sass/layout/_problems.scss
> +  // font-size: 24px; at the maquette
Убрать?

2021-07-04 21:08 UTC, vladislav-slobodenjuk commented on src/sass/layout/_problems.scss
> +.problems-list-block {
Здесь согласен. На рус макете они действительно одинаковые. Когда писал его еще не было

2021-07-04 21:20 UTC, vladislav-slobodenjuk commented on src/sass/layout/_problems.scss
> +.problems-title {
Это именно из-за фонтсайза заголовка, писал чуть выше. // font-size: 24px
Думал это ошибка дизайна, что 2 заголовка одного уровня h2 выбиваются из общего размера по странице. У всех 20px, даже у твоего h1 (!). А мой h2 больше остальных и больше h1.
Но если сделать 24, то станет ровно по макету.
Что скажешь?

2021-07-04 21:21 UTC, vladislav-slobodenjuk commented on src/sass/base/_container.scss
> +  // outline: 2px solid red;
Убрать?

2021-07-04 21:24 UTC, vladislav-slobodenjuk commented on src/sass/layout/_problems.scss
> +.problems-title {
Нашел. Еще заголовок "We guarantee" 26рх

2021-07-04 21:30 UTC, vladislav-slobodenjuk commented on src/sass/layout/_problems.scss
> +.problems-list-block {
Исправил

2021-07-05 08:43 UTC, Dron010 commented on src/partials/problems.html
> +            </ol>
Список проблем оформить как сетку элементов. Для нумерации пунктов 
списка используйте css-счетчики.
https://developer.mozilla.org/ru/docs/Web/CSS/CSS_Lists_and_Counters/Using_CSS_counters

2021-07-05 10:10 UTC, vladislav-slobodenjuk commented on src/partials/problems.html
> +            </ol>
Что ты имеешь в виду здесь? Стили счётчиков в scss

2021-07-05 10:21 UTC, vladislav-slobodenjuk commented on src/sass/base/_container.scss
> +  // outline: 2px solid red;
Gfe

2021-07-05 10:23 UTC, Viktor-Kostiuchenko requested changes

2021-07-05 10:23 UTC, Viktor-Kostiuchenko commented on src/sass/layout/_problems.scss
> +.problems-list {
Со счетчиками вроде вообще все гуд! Красава!)

2021-07-05 10:23 UTC, Viktor-Kostiuchenko commented on src/sass/base/_container.scss
> +  // outline: 2px solid red;
Вообще не критично, просто можно сразу убрать, чтобы потом не забыть (либо просто потом не забыть)

2021-07-05 10:23 UTC, Viktor-Kostiuchenko commented on src/sass/layout/_problems.scss
> +  .problems-container {
У тебя ж еще для десктопной версии должен быть огонь на фоне

2021-07-05 10:23 UTC, Viktor-Kostiuchenko commented on src/sass/layout/_problems.scss
> +  // font-size: 24px; at the maquette
У меня показывает в русской версии: 
для моблики = 20
для таблетки = 26
для десктопа = 46

в английской версии: 
для моблики = 24
для таблетки = 24
для десктопа = 46

2021-07-05 10:23 UTC, Viktor-Kostiuchenko commented on src/sass/layout/_problems.scss
> +.problems-title {
Я там написал Алене чтобы дала нам нормальный макет, потому что это не дело

2021-07-05 10:23 UTC, Viktor-Kostiuchenko commented on src/sass/base/_container.scss
> +  // outline: 2px solid red;
убирай да и все)

2021-07-05 10:23 UTC, Viktor-Kostiuchenko commented on src/sass/layout/_problems.scss
> +.problems-title {
Пришел новый макет. Можно по нему сверить да и норм

2021-07-05 15:56 UTC, vladislav-slobodenjuk commented on src/sass/layout/_problems.scss
> +.problems-title {
Выровнял

2021-07-05 15:57 UTC, vladislav-slobodenjuk commented on src/sass/layout/_problems.scss
> +.problems-list-block {
Исправил

2021-07-05 15:57 UTC, vladislav-slobodenjuk commented on src/sass/layout/_problems.scss
> +.problems-list {
Грасиас =)

2021-07-05 18:04 UTC, vladislav-slobodenjuk commented on src/sass/layout/_problems.scss
> +  .problems-container {
Добавил

2021-07-05 18:07 UTC, vladislav-slobodenjuk commented
padding-top for container
font-size for title
for problems-list-block:
	all paddings
	line-height
	set color
margin-bottom for problems-item
margin-top for items at flex

2021-07-05 20:19 UTC, Viktor-Kostiuchenko approved these changes

2021-07-05 20:19 UTC, merged